### ISSUE TITLE
Unable to run installed Lua packages

### ISSUE THREAD

**Issue by HendrikJan** [bitnami/bitnami-docker-openresty#2]
### Name and Version

bitnami/openresty:latest

### What steps will reproduce the bug?

1. Install Lua packages to be used with Nginx like this:

```dockerfile
FROM bitnami/openresty:latest

USER root
RUN mkdir /.opm
RUN touch /.opmrc
RUN chown 1001:1001 /.opm
RUN chown 1001:1001 /.opmrc
RUN chmod -R a+rw /opt/bitnami/openresty

USER 1001

RUN echo "download_server = https://opm.openresty.org" > /.opmrc

# Now install lua-resty-openidc
RUN opm install zmartzone/lua-resty-openidc

WORKDIR /var/www/html
```

2. Add this to **server_blocks/my_server_block.conf**:
```nginx
# Lua settings for OpenID
lua_package_path '~/lua/?.lua;;';
resolver 8.8.8.8;
lua_ssl_trusted_certificate /etc/ssl/jurassicjs.eu/fullchain.pem;
lua_ssl_verify_depth 5;
# cache for discovery metadata documents
lua_shared_dict discovery 1m;
# cache for JWKs
lua_shared_dict jwks 1m;

server {
   ....
   location / {
        access_by_lua_block {
            ....
            -- call authenticate for OpenID Connect user authentication
            local res, err = require("resty.openidc").authenticate(opts)
            ....
        }     
    }
}
```

3. See the error: **module 'resty.openidc' not found**

### What is the expected behavior?

I would expect there to be no error, because I installed `lua-resty-openidc`.
I would expect an openRusty server to be configured so that installed Lua packages can easily be installed.

### What do you see instead?

I see the error: `module 'resty.openidc' not found` in my terminal when I try to load the website

### Additional information

When building the Docker container I can see that Lua packages are being downloaded.
I get the following message in my terminal:
```error
Package zmartzone/lua-resty-openidc 1.7.5 installed successfully under /opt/bitnami/openresty/site/ .
```

But when go into the container using `docker exec -it mycontainer bash` and look in the folder `/opt/bitnami/openresty/site/`, then this folder only contains an empty folder `lualib`, so nothing seems to be installed.

**Comment by carrodher** [comment]
Probably this kind of installation requires root permission, can you try placing it between the `USER root` and `USER 1001` directives?
